server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}
        git:
#          uri: file:///Users/pyeondohun/IdeaProjects/git-local-repo
#          uri: file://D:\newIdeaWorkSpace\git-local-repo
          uri: https://github.com/bigbulgogiburger/spring-cloud-config
#          default-label: master